[package]
name = "armada-boot"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.2"
fdt = "0.1.5"
tinybmp = "0.7.0"
u8g2-fonts = "0.8.0"
uefi = { version = "0.41", features = ["alloc", "global_allocator", "logger", "panic_handler"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
